/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ketnoicsdl;

/**
 *
 * @author ADMIN
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class giaodien extends javax.swing.JFrame {

    /**
     * Creates new form giaodien
     */
    public giaodien() {
        initComponents();
        dodulieuvao_jtable();

    }
void dodulieuvao_jtable(){
       DefaultTableModel model = (DefaultTableModel) Jtbl_qlcb.getModel();
       // xoa tat ca cac hang cua jtabel
       model.setNumRows(0);
        //DefaultTableModel model = (DefaultTableModel) Jtbl_qlcb.getModel();
       ketnoicsdl_mysql kn = new ketnoicsdl_mysql();
        Connection con=kn.cnn;
         try{
            Statement stmt=con.createStatement();  
            String sql="select * from canbo";
            //System.out.println(sql);
            ResultSet rs=stmt.executeQuery(sql);  
            // hiển thị từng dòng trong kết quả câu truy vấn trả về
            while(rs.next()){
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)});
            }
            kn.dongketnoi();
        }
         catch(Exception e){ 
            System.out.println(e);
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_macb = new javax.swing.JTextField();
        int_tuoi = new javax.swing.JTextField();
        cbx_bac = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_tencb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbx_gioitinh = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_nganh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_congviec = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtbl_qlcb = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_diachi = new javax.swing.JTextField();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã cb*");

        jLabel2.setText("Tuổi cb*");

        jLabel3.setText("Bậc*");

        txt_macb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_macbActionPerformed(evt);
            }
        });

        cbx_bac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", " " }));

        jLabel4.setText("Tên cb*");

        jLabel5.setText("Giới tính*");

        cbx_gioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        jLabel6.setText("Ngành*");

        jLabel7.setText("Công việc*");

        Jtbl_qlcb.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Jtbl_qlcb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Macb", "TenCB", "Tuoi", "Gioi tinh", "Dia chi", "Bac", "Nganh", "Công viec"
            }
        ));
        jScrollPane1.setViewportView(Jtbl_qlcb);

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        jLabel8.setText("Địa chỉ*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(int_tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_macb)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_tencb)
                                        .addComponent(cbx_gioitinh, 0, 164, Short.MAX_VALUE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(114, 114, 114)
                                    .addComponent(btn_them)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel3)
                                    .addGap(22, 22, 22)
                                    .addComponent(cbx_bac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)
                                    .addGap(2, 2, 2)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt_nganh, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_congviec, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_sua)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_xoa))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_macb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txt_tencb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(int_tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbx_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbx_bac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_congviec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_sua)
                    .addComponent(btn_xoa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_macbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_macbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_macbActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
String macb =txt_macb.getText();
        String hoten = txt_tencb.getText();
        String gioitinh= cbx_gioitinh.getSelectedItem().toString();
        String diachi=txt_diachi.getText();
        int tuoi= Integer.parseInt(int_tuoi.getText());
        int bac=Integer.parseInt(cbx_bac.getSelectedItem().toString());
        String nganh= txt_nganh.getText();
        String congviec=txt_congviec.getText();
        qlcb ql =new qlcb();
        ql.themcb(macb, hoten, gioitinh, diachi, tuoi, bac, nganh, congviec, "congnhan");
        dodulieuvao_jtable();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
int row = Jtbl_qlcb.getSelectedRow(); // return =-1 nếu không chọn, index (0->n-1)
        if(row>=0){
            String macb =Jtbl_qlcb.getModel().getValueAt(row, 0).toString();
            qlcb ql =new qlcb();
            ql.xoacb(macb);
            dodulieuvao_jtable();
        }
        else{
            System.out.println("Vui lòng chọn dòng cần xóa");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
String macb =txt_macb.getText();
        if(macb.equals("")){
            System.out.println("Vui lòng chọn cán bộ cần chỉnh sửa");
        }
        else{
            String hoten = txt_tencb.getText();
            String gioitinh= cbx_gioitinh.getSelectedItem().toString();
            String diachi=txt_diachi.getText();
            int tuoi= Integer.parseInt(int_tuoi.getText());
            int bac=Integer.parseInt(cbx_bac.getSelectedItem().toString());
            String nganh= txt_nganh.getText();
            String congviec=txt_congviec.getText();
          qlcb ql =new qlcb();
          ql.suacb(macb, hoten, gioitinh, diachi, tuoi, bac, nganh, congviec, "congnhan");
           dodulieuvao_jtable();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_suaActionPerformed
private void Jtbl_qlcbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jtbl_qlcbMouseClicked
        // TODO add your handling code here:
    
        if(evt.getClickCount() == 1){
            int row = Jtbl_qlcb.rowAtPoint(evt.getPoint()); // select a row
            String macb =Jtbl_qlcb.getModel().getValueAt(row, 0).toString();
            String hoten =Jtbl_qlcb.getModel().getValueAt(row, 1).toString();
            String gioitinh =Jtbl_qlcb.getModel().getValueAt(row, 2).toString();
            String diachi =Jtbl_qlcb.getModel().getValueAt(row, 3).toString();
            String tuoi =Jtbl_qlcb.getModel().getValueAt(row, 4).toString();
            String bac="";
            if(Jtbl_qlcb.getModel().getValueAt(row, 5)!=null){
                bac=Jtbl_qlcb.getModel().getValueAt(row, 5).toString();
            }
            String nganh="";
            if(Jtbl_qlcb.getModel().getValueAt(row, 6)!=null){
                nganh =Jtbl_qlcb.getModel().getValueAt(row, 6).toString();
            }
            String congviec="";
            if(Jtbl_qlcb.getModel().getValueAt(row, 7) !=null){
               congviec =Jtbl_qlcb.getModel().getValueAt(row, 7).toString();
            }
            
            txt_macb.setText(macb);
            txt_tencb.setText(hoten);
            cbx_gioitinh.setSelectedItem(gioitinh);
            txt_diachi.setText(diachi);
            int_tuoi.setText(tuoi);
            cbx_bac.setSelectedItem(bac);
//            txt_nganh.setText(nganh);
//            txt_congviec.setText(congviec);
           //qlcb ql =new qlcb();
           
            //dodulieuvao_jtable();
        }
        else{
            System.out.println("Vui lòng chọn dòng cần chinh sua");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giaodien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jtbl_qlcb;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbx_bac;
    private javax.swing.JComboBox<String> cbx_gioitinh;
    private javax.swing.JTextField int_tuoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txt_congviec;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_macb;
    private javax.swing.JTextField txt_nganh;
    private javax.swing.JTextField txt_tencb;
    // End of variables declaration//GEN-END:variables
}
